spring:
  application:
    name: config-service
  config:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bwc0/Config-Repo
          clone-on-start: true

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include=*:

